const toggle=document.querySelector('.menu-toggle');
const nav=document.querySelector('.nav');
toggle?.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')!=='true';toggle.setAttribute('aria-expanded',String(open));nav?.classList.toggle('open',open);document.body.classList.toggle('menu-open',open)});
nav?.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{toggle?.setAttribute('aria-expanded','false');nav.classList.remove('open');document.body.classList.remove('menu-open')}));
if('IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.1});document.querySelectorAll('.reveal').forEach(element=>observer.observe(element))}else{document.querySelectorAll('.reveal').forEach(element=>element.classList.add('visible'))}
document.querySelectorAll('.filter').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(item=>item.classList.remove('active'));button.classList.add('active');const category=button.dataset.filter;document.querySelectorAll('.gallery-item').forEach(item=>item.classList.toggle('is-hidden',category!=='all'&&item.dataset.category!==category))}));
const lightbox=document.querySelector('.lightbox');const lightboxImage=lightbox?.querySelector('img');const closeButton=lightbox?.querySelector('button');let lastFocused;
function closeLightbox(){lightbox?.classList.remove('open');lastFocused?.focus()}
document.querySelectorAll('.gallery-item').forEach(item=>item.addEventListener('click',()=>{const source=item.querySelector('img');if(!lightbox||!lightboxImage||!source)return;lastFocused=item;lightboxImage.src=source.src;lightboxImage.alt=source.alt;lightbox.classList.add('open');closeButton?.focus()}));
closeButton?.addEventListener('click',closeLightbox);lightbox?.addEventListener('click',event=>{if(event.target===lightbox)closeLightbox()});document.addEventListener('keydown',event=>{if(event.key==='Escape')closeLightbox()});
document.querySelector('.form')?.addEventListener('submit',event=>{event.preventDefault();const data=new FormData(event.currentTarget);const subject=encodeURIComponent(`Website enquiry from ${data.get('name')}`);const body=encodeURIComponent(`Name: ${data.get('name')}\nEmail: ${data.get('email')}\nTelephone: ${data.get('telephone')}\n\n${data.get('message')}`);window.location.href=`mailto:hmukiibiu@gmail.com?subject=${subject}&body=${body}`});
